# Generated by Django 4.1.7 on 2023-03-07 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.TextField(blank=True, default=0, max_length=150, null=True)),
                ('token_activation_time', models.DateTimeField(auto_now_add=True)),
                ('token_last_usage', models.DateTimeField(blank=True, null=True)),
                ('token_delete_time', models.DateTimeField(blank=True, null=True)),
                ('api_token_password', models.TextField(blank=True, max_length=150, null=True)),
                ('api_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
