# Generated by Django 4.1.7 on 2023-03-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccesstoken',
            name='random_number',
            field=models.CharField(blank=True, default='23223434', max_length=10, unique=True),
        ),
    ]
